[build]
rustflags = [
  ## Warning ##
  "-Dclippy::pedantic",
  "-Dclippy::restriction",
  "-Dclippy::nursery",
  # "-Dclippy::cargo",
  ## Conflicts ##
  "-Aclippy::blanket_clippy_restriction_lints", # clippy::restriction                 - can't enable clippy::restriction if this is enabled
  "-Aclippy::implicit_return",                  # clippy::needless-return             - remove return keyword when not needed
  "-Aclippy::mod_module_files",                 # clippy::self_named_module_files     - `./foo/mod.rs` instead of (`./foo.rs` + `./foo/*.rs`)
  "-Aclippy::separated_literal_suffix",         # clippy::unseparated-literal-suffix  - 2.0_f32 vs 2.0f32
  ## Allowed ##
  "-Aclippy::float-arithmetic",                 # used during evaluation
  "-Aclippy::modulo-arithmetic",                # used during evaluation
  "-Aclippy::undocumented-unsafe-blocks",       # ok to not document if using `trust_me!` macro (if we are 100% sure)
  ## Maybe remove ##
  "-Aclippy::single_char_lifetime_names",       # common practice to use 'a
]
