[build]
rustflags = [
  ## Warning ##
  "-Wclippy::pedantic",
  "-Wclippy::restriction",
  "-Wclippy::nursery",
  # "-Wclippy::cargo",
  ## Allowed ##
  "-Aclippy::arithmetic-side-effects",          # cursor increment in parsing/lexing and evaluation
  "-Aclippy::blanket_clippy_restriction_lints", # allow `clippy::restriction` to be used globally
  "-Aclippy::implicit_return",                  # convenience
  "-Aclippy::question_mark_used",               # convenience
  "-Aclippy::separated_literal_suffix",         # allows 2.0_f32
  "-Aclippy::single_call_fn",                   # function only called once
  "-Aclippy::single_char_lifetime_names",       # common practice to use 'a, to remove ?
  "-Aclippy::pub-with-shorthand",               # pub(<scope>) instead of pub(in <scope>)
  ## Must remove ##
  "-Aclippy::missing_docs_in_private_items",
  "-Aclippy::missing-errors-doc",
  "-Aclippy::mod_module_files",
  "-Aclippy::print_stdout",
  "-Aclippy::print_stderr",
  "-Aclippy::undocumented-unsafe-blocks",
  "-Aclippy::use_debug",
]
