name: CI

on:
  workflow_call:
    inputs:
      rust-version:
        required: true
        type: string
      enabled-feature-set:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "rust-version: ${{ inputs.rust-version }}"
          echo "enabled-feature-set: ${{ inputs.enabled-feature-set }}"
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust-version }}
      - run: cargo check --no-default-features --features ${{ inputs.enabled-feature-set }}

  # tests:
  #   needs: build
  #   runs-on: ${{ inputs.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Rust
  #       uses: IronCoreLabs/rust-toolchain@v1
  #       with:
  #         toolchain: ${{ inputs.rust-version }}
  #     - run: cargo test --no-default-features --features ${{ inputs.enabled-feature-set }}

  # miri:
  #   needs: build
  #   runs-on: ${{ inputs.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Rust
  #       uses: IronCoreLabs/rust-toolchain@v1
  #       with:
  #         toolchain: ${{ inputs.rust-version }}
  #     - run: cargo miri setup
  #     - run: cargo miri test --no-default-features --features ${{ inputs.enabled-feature-set }}
  #       env:
  #         MIRIFLAGS: -Zmiri-strict-provenance
