name: Rust fmt & clippy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Rust fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
        with:
          toolchain: nightly
      ### Pemdas
      - name: Run clippy (`pemdas` & `compile-time-optimizations`)
        run: cargo clippy --no-default-features --features pemdas --features compile-time-optimizations
      - name: Run clippy (`pemdas` feature)
        run: cargo clippy --no-default-features --features pemdas
      ### Pejmdas
      - name: Run clippy (`pejmdas` & `compile-time-optimizations` feature)
        run: cargo clippy --no-default-features --features pejmdas --features compile-time-optimizations
      - name: Run clippy (`pejmdas` feature)
        run: cargo clippy --no-default-features --features pejmdas
