name: Rust fmt & clippy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
      - name: Rust fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
      - name: Rust clippy (default features, currently `pemdas`)
        run: cargo clippy
      - name: Rust clippy (`pejmdas` feature)
        run: cargo clippy --no-default-features --features pejmdas
