name: Rust fmt & clippy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
      - name: Rust fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
      - name: Rust clippy
        run: cargo clippy --all --all-targets
