name: Fmt

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: IronCoreLabs/rust-toolchain@v1
      with:
        toolchain: nightly
    - name: Rust fmt
      run: cargo fmt --all -- --check
