name: Setup Matrix

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@master

  setup_matrix:
    needs: pre_ci
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly, 1.70.0]
        enabled-feature-set:
          [
            "pemdas",
            "pemdas compile-time-optimizations",
            "pejmdas",
            "pejmdas compile-time-optimizations",
          ]
    uses: ./.github/workflows/ci.yml
    with:
      os: ${{ matrix.os }}
      rust-version: ${{ matrix.rust }}
      enabled-feature-set: ${{ matrix.enabled-feature-set }}
    secrets: inherit
