name: Setup Matrix

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # pre_ci:
  #   uses: dtolnay/.github/.github/workflows/pre_ci.yml@master

  setup_matrix:
    # needs: pre_ci
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly, 1.70.0]
        enabled-feature-set: [
          "pemdas",
          "pemdas compile-time-optimizations",
          "pejmdas",
          "pejmdas compile-time-optimizations",
        ]
    uses: ./.github/workflows/ci.yml
    with:
      rust-version: ${{ matrix.rust }}
      enabled-feature-set: ${{ matrix.enabled-feature-set }}
    secrets: inherit
