name: Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: IronCoreLabs/rust-toolchain@v1
      - name: Run tests (default features, currently `pemdas`)
        run: cargo test
      - name: Run tests (`pejmdas` feature)
        run: cargo test --no-default-features --features pejmdas
